runtime: python39
entrypoint: gunicorn -b :$PORT app:App

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

instance_class: F2

handlers:
- url: /.*
  script: auto
